### PR TITLE
Support both ghc-8.6 and ghc-8.8

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Comment by mrBliss** [comment]
We should have CI build both 8.6 and 8.8 (and 8.10?). Unfortunately, that requires some Nix knowledge I lack.

**Comment by erikd** [comment]
> We should have CI build both 8.6 and 8.8 (and 8.10?). Unfortunately, that requires some Nix knowledge I lack.

I don't think that is a great idea. Our CI infrastructure is already groaning under the weight ot our current requirements, before doubling or even tripling it.

I think the best way of doing this is update everything to use both 8.6 and 8.8 in as short an amount of time as possible, then switch CI to only use 8.8.

As for 8.10, i would like to make that switch, but past experience suggests that switching to version `1` of the compiler (eg 8.10.1) is unwise. Its usually best to wait until at least 8.10.2.

**Comment by mrBliss** [comment]
> > We should have CI build both 8.6 and 8.8 (and 8.10?). Unfortunately, that requires some Nix knowledge I lack.
> 
> I don't think that is a great idea. Our CI infrastructure is already groaning under the weight ot our current requirements, before doubling or even tripling it.

As long as CI is not building/testing with 8.8, we can accidentally break it. (That's the whole point of CI)

It's true that CI is already slow and unreliable enough. But maybe for simple and infrequently updated libraries like `cardano-prelude`, `cardano-base`, and `cardano-crypto`, the additional CI load could bearable.

> 
> I think the best way of doing this is update everything to use both 8.6 and 8.8 in as short an amount of time as possible, then switch CI to only use 8.8.

I'm curious, is there a plan/timeline for the transition?

> 
> As for 8.10, i would like to make that switch, but past experience suggests that switching to version `1` of the compiler (eg 8.10.1) is unwise. Its usually best to wait until at least 8.10.2.

Sure. My idea was not to switch to it, but to make the library compatible with it, or rather, to prevent making it *incompatible* with it.



If we just want to switch from 8.6 to 8.8, sure, then this is fine for now. But if we really want to be developing our code "as libraries" like discussed on Slack, then we should be testing with more than 8.6.

**Comment by nc6** [comment]
One issue is that we don't necessarily have to pay the CI price on _every_ repo. E.g. currently, Plutus are the main drivers for wanting GHC 8.8. They will presumably be testing with it, which will include testing this repo. For the infrequency of changes, it's probably fine if we don't discover specific problems with 8.8 until we hit the Plutus repo.

It can then become a choice for each team whether to enable GHC8.8 testing on their repos, depending on the balance between finding bugs earlier in the hierarchy and increasing CI times.

**Comment by nc6** [comment]
bors merge

**Pull request merged**
