### PR TITLE
Make it build with ghc-9.8

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Review by lehins — APPROVED** [review]
:+1:

**Comment by lehins** [comment]
You might wanna set this line to `latest`
https://github.com/input-output-hk/cardano-prelude/blob/39a4235a2502a621da96648da88aa6fc6c1efaeb/.github/workflows/haskell.yml#L26

**Comment by erikd** [comment]
@lehins Using:
```
        cabal-version: latest
```
trys to install `3.6.2.0` and that fails.

**Comment by lehins** [comment]
Change this line to `haskell-actions/setup@v2`:
https://github.com/input-output-hk/cardano-prelude/blob/39a4235a2502a621da96648da88aa6fc6c1efaeb/.github/workflows/haskell.yml#L22

**Comment by angerman** [comment]
LGTM. #193 tries to address the nix related issues.

**Pull request merged**
