### PR TITLE
Fix build with nonempty-containers >=0.3.4

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by hasufell** [comment]
ping

**Comment by mrBliss** [comment]
Is anybody even using `NESet`? I don't think that `cardano-node` or any of its upstream repos use it. If the wallet doesn't use it either, I would just remove the dependency all together.

FYI, the goal of a few of us (from node-related teams) is to move away from `cardano-prelude`. After splitting off `NoUnexpectedThunks` into https://hackage.haskell.org/package/nothunks (#124), I think the only thing left are the strict variants of some data types, which will be part of another library @edsko is working on.

(If you just want to get this merged, rebase and ping me)

**Comment by hasufell** [comment]
cardano-prelude is part of https://raw.githubusercontent.com/input-output-hk/cardano-haskell/cfe917f0f419b5c9f63c958f335874e4dc0add85/snapshots/cardano-1.20.0.yaml and is automatically built.

**Comment by hasufell** [comment]
However it seem @newhoggy has changed this with https://github.com/input-output-hk/cardano-prelude/commit/e74fa90e33a5a1ac5815c5286a2347ed9e1988b4#diff-7d3b4b25c2dea6c1b0a112138cb4388e

**Comment by mrBliss** [comment]
> cardano-prelude is part of https://raw.githubusercontent.com/input-output-hk/cardano-haskell/cfe917f0f419b5c9f63c958f335874e4dc0add85/snapshots/cardano-1.20.0.yaml and is automatically built.

I'm not sure I follow. I was talking about removing the dependency on `nonempty-containers`, not `cardano-prelude` (although that is indeed the goal in the future, as I also mentioned).

> However it seem @newhoggy has changed this with [e74fa90#diff-7d3b4b25c2dea6c1b0a112138cb4388e](https://github.com/input-output-hk/cardano-prelude/commit/e74fa90e33a5a1ac5815c5286a2347ed9e1988b4#diff-7d3b4b25c2dea6c1b0a112138cb4388e)

So this PR is no longer needed, correct?

**Comment by hasufell** [comment]
> So this PR is no longer needed, correct?

The current commit won't work well with stack, which requires an older version of nonempty-containers: https://www.stackage.org/lts-14.25/package/nonempty-containers-0.3.1.0

**Comment by mrBliss** [comment]
> > So this PR is no longer needed, correct?
> 
> The current commit won't work well with stack, which requires an older version of nonempty-containers: https://www.stackage.org/lts-14.25/package/nonempty-containers-0.3.1.0

Ok, so what about my suggestion of removing the dependency on `nonempty-containers` (and the instances from the code) altogether? If nobody uses it and it is causing problems for Stack user (you could always override the dependency to a newer one), then it's easiest to avoid the issue entirely by removing it.

**Comment by hasufell** [comment]
> Ok, so what about my suggestion of removing the dependency on nonempty-containers (and the instances from the code) altogether?

I'd have to test with the wallet first if it builds and I haven't rebased the ghc-8.10.2 branch in a while, so I might pick this up only once I work on that branch again.

**Comment by mrBliss** [comment]
> > Ok, so what about my suggestion of removing the dependency on nonempty-containers (and the instances from the code) altogether?
> 
> I'd have to test with the wallet first if it builds and I haven't rebased the ghc-8.10.2 branch in a while, so I might pick this up only once I work on that branch again.

Sure. You could do a grep for any of the modules in https://hackage.haskell.org/package/nonempty-containers (or just the package name) in the wallet repo and if you get no hits, you can be sure. If you do get hits, then building is the surest option to check whether you the instances `FromJSON` and `ToJSON` instances in question.

It seems that https://github.com/input-output-hk/cardano-wallet/search?q=nonempty-containers only gives hits because the `cardano-prelude` uses the package, not because the wallet actually uses it, so I believe it is safe to remove the dependency (unless we should check other repos?)

**Comment by newhoggy** [comment]
Any updates on what to do with this PR?

**Comment by mrBliss** [comment]
> Any updates on what to do with this PR?

If @hasufell still needs this, he should reply.

My 2c: either do nothing or just remove `nonempty-containers` and the instances from `cardano-prelude`. But my plan is to dismantle/abandon `cardano-prelude` altogether, so I'm biased. :slightly_smiling_face:.

**Comment by hasufell** [comment]
> Any updates on what to do with this PR?

I haven't started working on GHC-8.10.2 migration in wallet yet. It seems it isn't prioritized. Is the node already migrated?

**Comment by mrBliss** [comment]
> > Any updates on what to do with this PR?
> 
> I haven't started working on GHC-8.10.2 migration in wallet yet. It seems it isn't prioritized. Is the node already migrated?

We're working on it. @coot is working on a fix for https://twitter.com/ndm_haskell/status/1313181853822717952 that doesn't require us waiting on the release of GHC 8.10.3. If that works out, `ouroboros-network` will switch over to GHC 8.10.2 quickly and with help from @newhoggy the node can follow after that.

**Comment by newhoggy** [comment]
Seems like `nonempty-containers` is no longer a dependency.  Shall I close this PR?

**Comment by mrBliss** [comment]
> Seems like `nonempty-containers` is no longer a dependency. Shall I close this PR?

Ha, indeed, I didn't realise that. Good! :slightly_smiling_face:

**Pull request closed without merging**
